blank_issues_enabled: true
contact_links:
    - name: "Start a discussion (GitHub)" 
      about: "How do I…?"
      url: https://github.com/scikit-hep/awkward-1.0/discussions/new
    - name: "StackOverflow: [awkward-array] tag" 
      about: "How do I…?"
      url: https://stackoverflow.com/questions/tagged/awkward-array
    - name: "Gitter: Scikit-HEP/awkward-array room"
      about: "Getting help in real-time…"
      url: https://gitter.im/Scikit-HEP/awkward-array
